### ISSUE TITLE
/knetresponce/success/ url not found

### ISSUE THREAD

**Issue by webymaster** [alnazer/wc-knet#1]
For some reason after successful payment and redirection back the defined URL doesn't work.
Do I have to add it to .htaccess or do anything other than defining the KNET parameters?

**Comment by alnazer** [comment]
Excuse me for the late reply
I added this route in WordPress. Let me confirm

**Comment by alnazer** [comment]
can you send me screenshot of the error

**Comment by alnazer** [comment]
now i fixed it will work  Insha'Allah
